[package]
name = "unty"
version = "0.0.0"
edition = "2021"
description = "Explicitly types your generics"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/bincode-org/unty"
authors = ["Victor Koenders <bincode@trang.ar>"]
